import { z } from 'zod';
export const stageLabels = { not_started: 'Not started', in_progress: 'In progress', completed: 'Completed', blocked: 'Needs attention', not_applicable: 'Not applicable' } as const;
export const participationLabels = { undecided: 'Undecided', yes: 'Participating', no: 'Not participating' } as const;
export const resultLabels = { pending: 'Awaiting result', allotted: 'Allotted', not_allotted: 'Not allotted', withheld: 'Withheld', not_applicable: 'Not applicable' } as const;
export const completionLabels = { ongoing: 'Counselling ongoing', done: 'Counselling done', withdrawn: 'Withdrawn' } as const;
const text = (max: number) => z.string().trim().max(max);
const stage = z.enum(['not_started','in_progress','completed','blocked','not_applicable']);
export const roundSchema = z.object({ round: z.number().int().min(1).max(4), participation: z.enum(['undecided','yes','no']), registration: stage, choices: stage, verification: stage, result: z.enum(['pending','allotted','not_allotted','withheld','not_applicable']), college: text(500), course: text(100), quota: text(100), category: text(100), decision: z.enum(['pending','freeze','float','upgrade','withdraw','joined']), reporting: stage, reportingDate: text(10), sourceUrl: text(1500).refine(v => !v || /^https?:\/\//i.test(v), 'Use an http or https source link'), notes: text(2000) }).superRefine((r,ctx)=>{if(r.result==='allotted'&&!r.college)ctx.addIssue({code:'custom',message:'Enter the college name for an allotted result'});if(r.decision==='joined'&&r.result!=='allotted')ctx.addIssue({code:'custom',message:'Mark the result as allotted before recording joined'});});
export const enrollmentSchema = z.object({ id: text(100).min(1), counselling: text(160).min(1), year: z.number().int().min(2020).max(2100), registrationNumber: text(100), listId: text(120), status: z.enum(['ongoing','done','withdrawn']), rounds: z.array(roundSchema).length(4).refine(a => new Set(a.map(r => r.round)).size === 4, 'Include each round once') });
export const directorySchema = z.object({ name: text(100).min(1,'Student name is required'), applicationNumber: text(100), mobile: text(30), email: text(160).refine(v=>!v || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v),'Enter a valid email'), neetRank: text(20).refine(v=>!v || /^[1-9]\d*$/.test(v),'Enter a valid NEET rank'), counsellor: text(100), priority: z.enum(['normal','urgent','low']), nextAction: text(500), followUpDate: text(10), notes: text(4000), completion: z.enum(['ongoing','done','withdrawn']), enrollments: z.array(enrollmentSchema).max(60) }).superRefine((s,ctx)=>{const keys=s.enrollments.map(e=>e.counselling.toLowerCase()+'|'+e.year); if(new Set(keys).size!==keys.length)ctx.addIssue({code:'custom',message:'Add each counselling only once per year'});const links=s.enrollments.map(e=>e.listId).filter(Boolean);if(new Set(links).size!==links.length)ctx.addIssue({code:'custom',message:'A choice list can be linked only once'});if(s.completion==='done' && (!s.enrollments.length || s.enrollments.some(e=>e.status==='ongoing')))ctx.addIssue({code:'custom',message:'Complete or withdraw each counselling before marking this student done'});});
export type DirectoryDraft = z.infer<typeof directorySchema>;
export type Enrollment = z.infer<typeof enrollmentSchema>;
export type DirectoryStudent = DirectoryDraft & { id: string; revision: number; updatedAt: number; archivedAt: number | null };
export type ExistingList = { id: string; studentName: string; masterTitle: string; linkedStudentId: string | null; choiceLockedAt: number | null };
export function newEnrollment(counselling = ''): Enrollment { return { id: crypto.randomUUID(), counselling, year: new Date().getFullYear(), registrationNumber: '', listId: '', status: 'ongoing', rounds: [1,2,3,4].map(round=>({round,participation:'undecided',registration:'not_started',choices:'not_started',verification:'not_started',result:'pending',college:'',course:'',quota:'',category:'',decision:'pending',reporting:'not_started',reportingDate:'',sourceUrl:'',notes:''})) }; }
export function newStudent(): DirectoryDraft { return {name:'',applicationNumber:'',mobile:'',email:'',neetRank:'',counsellor:'',priority:'normal',nextAction:'',followUpDate:'',notes:'',completion:'ongoing',enrollments:[]}; }
export function needsAttention(s: DirectoryDraft) { return s.completion==='ongoing' && (s.priority==='urgent' || (!!s.followUpDate && s.followUpDate < new Date().toISOString().slice(0,10)) || s.enrollments.some(e=>e.rounds.some(r=>r.participation==='yes' && [r.registration,r.choices,r.verification,r.reporting].includes('blocked')))); }
